[env:m5stack-cores3]
platform = espressif32 @ 7.0.1
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
upload_speed = 1500000

build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1

lib_deps =
  m5stack/M5Unified @ 0.2.19
  adafruit/Adafruit NeoPixel @ 1.13.0
  https://github.com/Rupakpoddar/ESP32Sonos.git#58e89653ac1b8692328e63eecfb6bbf86d69b863
